INFO     user_service:user_service.py:47 Starting the process to view the user.
INFO     auth_service:authentification.py:10 Initializing Auth class.
INFO     auth_service:authentification.py:17 Loading credential configuration from 'credentials.json'.
INFO     auth_service:authentification.py:13 Auth class initialized successfully.
INFO     auth_service:authentification.py:37 Building headers for user type: 'invalid_user'
INFO     auth_service:authentification.py:28 Fetching user details for user type: 'invalid_user'
INFO     auth_manager:auth_manager.py:18 Building headers for user: invalid
INFO     auth_manager:auth_manager.py:9 Encoding credentials for user: invalid
INFO     auth_manager:auth_manager.py:28 Headers build successfully for user: invalid
INFO     auth_service:authentification.py:47 Headers successfully built for user type: 'invalid_user'
INFO     api_manager:api_request.py:12 GET Request URL: https://unitest.espocloud.com/api/v1/User/66e20635971c3244f | {'Espo-Authorization': 'aW52YWxpZDppbnZhbGlk', 'X-Api-Key': '4c29fe9482f3bccb7ac0a7d04015a2e7'}
INFO     api_manager:api_request.py:14 Response Status Code: 401
INFO     user_service:user_service.py:51 Finished processing the user view request.
INFO     status_code_assertion:status_code_assertion.py:47 Validating status code 401 for response with URL: https://unitest.espocloud.com/api/v1/User/66e20635971c3244f
INFO     status_code_assertion:status_code_assertion.py:52 Status code 401 validated successfully.