INFO     user_service:user_service.py:11 Starting the process to get the user list.
INFO     auth_service:authentification.py:10 Initializing Auth class.
INFO     auth_service:authentification.py:17 Loading credential configuration from 'credentials.json'.
INFO     auth_service:authentification.py:13 Auth class initialized successfully.
INFO     auth_service:authentification.py:37 Building headers for user type: 'valid_user'
INFO     auth_service:authentification.py:28 Fetching user details for user type: 'valid_user'
INFO     auth_manager:auth_manager.py:18 Building headers for user: admin
INFO     auth_manager:auth_manager.py:9 Encoding credentials for user: admin
INFO     auth_manager:auth_manager.py:28 Headers build successfully for user: admin
INFO     auth_service:authentification.py:47 Headers successfully built for user type: 'valid_user'
INFO     api_manager:api_request.py:12 GET Request URL: https://unitest.espocloud.com/api/v1/User?userType=unknown&select=isActive%2CemailAddressIsOptedOut%2CemailAddressIsInvalid%2CemailAddress%2CemailAddressData%2Ctitle%2CuserName%2CsalutationName%2CfirstName%2ClastName%2CmiddleName%2Cname&maxSize=20&offset=0&orderBy=userName&order=asc | {'Espo-Authorization': 'YWRtaW46ODAwNDkwNTM=', 'X-Api-Key': '4c29fe9482f3bccb7ac0a7d04015a2e7'}
INFO     api_manager:api_request.py:14 Response Status Code: 200
INFO     user_service:user_service.py:15 Finished processing the user list request.
INFO     status_code_assertion:status_code_assertion.py:9 Validating status code 200 for response with URL: https://unitest.espocloud.com/api/v1/User?userType=unknown&select=isActive%2CemailAddressIsOptedOut%2CemailAddressIsInvalid%2CemailAddress%2CemailAddressData%2Ctitle%2CuserName%2CsalutationName%2CfirstName%2ClastName%2CmiddleName%2Cname&maxSize=20&offset=0&orderBy=userName&order=asc
INFO     status_code_assertion:status_code_assertion.py:14 Status code 200 validated successfully.
INFO     status_code_assertion:status_code_assertion.py:16 Response body is not empty.
INFO     content_assertion:general_assertion.py:115 Validating field 'total'. Expected: '0', Found: '0'.