INFO     user_service:user_service.py:29 Starting the process to delete a user.
INFO     auth_service:authentification.py:10 Initializing Auth class.
INFO     auth_service:authentification.py:17 Loading credential configuration from 'credentials.json'.
INFO     auth_service:authentification.py:13 Auth class initialized successfully.
INFO     auth_service:authentification.py:37 Building headers for user type: 'valid_user'
INFO     auth_service:authentification.py:28 Fetching user details for user type: 'valid_user'
INFO     auth_manager:auth_manager.py:18 Building headers for user: admin
INFO     auth_manager:auth_manager.py:9 Encoding credentials for user: admin
INFO     auth_manager:auth_manager.py:28 Headers build successfully for user: admin
INFO     auth_service:authentification.py:47 Headers successfully built for user type: 'valid_user'
INFO     api_manager:api_request.py:45 DELETE Request URL: https://unitest.espocloud.com/api/v1/User/invalid | {'Espo-Authorization': 'YWRtaW46ODAwNDkwNTM=', 'X-Api-Key': '4c29fe9482f3bccb7ac0a7d04015a2e7', 'Content-Type': 'application/json'}
INFO     api_manager:api_request.py:47 Response Status Code: 404
INFO     user_service:user_service.py:33 Finished processing the delete user request.
INFO     status_code_assertion:status_code_assertion.py:59 Validating status code 404 for response with URL: https://unitest.espocloud.com/api/v1/User/invalid
INFO     status_code_assertion:status_code_assertion.py:64 Status code 404 validated successfully.