{"uid":"648ea54366bbef0f","name":"test_view_deleted_team_returns_404","fullName":"test.teams.test_get_team#test_view_deleted_team_returns_404","historyId":"3fea3e59d795af85e5e11d6bcdacd986","time":{"start":1728316497516,"stop":1728316498172,"duration":656},"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError: Expected status code 404, but got 200. Response text: {\"id\":\"67040451718df6165\",\"name\":\"Team test type\",\"deleted\":true,\"positionList\":[\"Designer\",\"Dev\",\"Scrum Master\"],\"createdAt\":\"2024-10-07 15:54:57\",\"modifiedAt\":\"2024-10-07 15:54:57\",\"rolesIds\":[\"6703f64ba26bb589d\",\"6703f804da5feb1b0\"],\"rolesNames\":{\"6703f64ba26bb589d\":\"Administrador\",\"6703f804da5feb1b0\":\"Mortal\"},\"layoutSetId\":\"6703f89e1996ee098\",\"layoutSetName\":\"layaout\",\"workingTimeCalendarId\":\"6703f8ace83cd97ed\",\"workingTimeCalendarName\":\"calendar\"}","statusTrace":"setup_teardown_team_module = {'createdAt': '2024-10-07 15:54:57', 'deleted': False, 'id': '67040451718df6165', 'layoutSetId': '6703f89e1996ee098', ...}\n\n    @pytest.mark.viewteam\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\", condition=True)\n    def test_view_deleted_team_returns_404(setup_teardown_team_module):\n        team = setup_teardown_team_module\n        url = EndpointTeams.get_team_id(team['id'])\n        TeamService.delete_team(url)\n        response = TeamService.view_team(url)\n>       AssertionManager.assert_status_code_404(response)\n\ntest/teams/test_get_team.py:31: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [200]>\n\n    @staticmethod\n    def assert_status_code_404(response):\n        logger.info(f\"Validating status code 404 for response with URL: {response.url}\")\n        try:\n>           assert response.status_code == 404, (\n                f\"Expected status code 404, but got {response.status_code}. Response text: {response.text}\"\n            )\nE           AssertionError: Expected status code 404, but got 200. Response text: {\"id\":\"67040451718df6165\",\"name\":\"Team test type\",\"deleted\":true,\"positionList\":[\"Designer\",\"Dev\",\"Scrum Master\"],\"createdAt\":\"2024-10-07 15:54:57\",\"modifiedAt\":\"2024-10-07 15:54:57\",\"rolesIds\":[\"6703f64ba26bb589d\",\"6703f804da5feb1b0\"],\"rolesNames\":{\"6703f64ba26bb589d\":\"Administrador\",\"6703f804da5feb1b0\":\"Mortal\"},\"layoutSetId\":\"6703f89e1996ee098\",\"layoutSetName\":\"layaout\",\"workingTimeCalendarId\":\"6703f8ace83cd97ed\",\"workingTimeCalendarName\":\"calendar\"}\n\ncore/assertions/status_code_assertion.py:61: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1728316483339,"stop":1728316483355,"duration":16},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_teardown_team_module","time":{"start":1728316497177,"stop":1728316497516,"duration":339},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError: Expected status code 404, but got 200. Response text: {\"id\":\"67040451718df6165\",\"name\":\"Team test type\",\"deleted\":true,\"positionList\":[\"Designer\",\"Dev\",\"Scrum Master\"],\"createdAt\":\"2024-10-07 15:54:57\",\"modifiedAt\":\"2024-10-07 15:54:57\",\"rolesIds\":[\"6703f64ba26bb589d\",\"6703f804da5feb1b0\"],\"rolesNames\":{\"6703f64ba26bb589d\":\"Administrador\",\"6703f804da5feb1b0\":\"Mortal\"},\"layoutSetId\":\"6703f89e1996ee098\",\"layoutSetName\":\"layaout\",\"workingTimeCalendarId\":\"6703f8ace83cd97ed\",\"workingTimeCalendarName\":\"calendar\"}","statusTrace":"setup_teardown_team_module = {'createdAt': '2024-10-07 15:54:57', 'deleted': False, 'id': '67040451718df6165', 'layoutSetId': '6703f89e1996ee098', ...}\n\n    @pytest.mark.viewteam\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\", condition=True)\n    def test_view_deleted_team_returns_404(setup_teardown_team_module):\n        team = setup_teardown_team_module\n        url = EndpointTeams.get_team_id(team['id'])\n        TeamService.delete_team(url)\n        response = TeamService.view_team(url)\n>       AssertionManager.assert_status_code_404(response)\n\ntest/teams/test_get_team.py:31: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [200]>\n\n    @staticmethod\n    def assert_status_code_404(response):\n        logger.info(f\"Validating status code 404 for response with URL: {response.url}\")\n        try:\n>           assert response.status_code == 404, (\n                f\"Expected status code 404, but got {response.status_code}. Response text: {response.text}\"\n            )\nE           AssertionError: Expected status code 404, but got 200. Response text: {\"id\":\"67040451718df6165\",\"name\":\"Team test type\",\"deleted\":true,\"positionList\":[\"Designer\",\"Dev\",\"Scrum Master\"],\"createdAt\":\"2024-10-07 15:54:57\",\"modifiedAt\":\"2024-10-07 15:54:57\",\"rolesIds\":[\"6703f64ba26bb589d\",\"6703f804da5feb1b0\"],\"rolesNames\":{\"6703f64ba26bb589d\":\"Administrador\",\"6703f804da5feb1b0\":\"Mortal\"},\"layoutSetId\":\"6703f89e1996ee098\",\"layoutSetName\":\"layaout\",\"workingTimeCalendarId\":\"6703f8ace83cd97ed\",\"workingTimeCalendarName\":\"calendar\"}\n\ncore/assertions/status_code_assertion.py:61: AssertionError","steps":[],"attachments":[{"uid":"24eeeeadcec8d9c4","name":"log","source":"24eeeeadcec8d9c4.txt","type":"text/plain","size":5873},{"uid":"d7ff791b3b851005","name":"stderr","source":"d7ff791b3b851005.txt","type":"text/plain","size":6162}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true},"afterStages":[{"name":"setup_teardown_team_module::0","time":{"start":1728316498202,"stop":1728316498531,"duration":329},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"},{"name":"tag","value":"viewteam"},{"name":"parentSuite","value":"test.teams"},{"name":"suite","value":"test_get_team"},{"name":"host","value":"fv-az1535-56"},{"name":"thread","value":"2094-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.teams.test_get_team"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["viewteam","@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"]},"source":"648ea54366bbef0f.json","parameterValues":[]}